#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2-stretch-slim AS base
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT docker
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/core/sdk:2.2-stretch AS build
WORKDIR /src
COPY ["MS.AFORO255.Gateway/MS.AFORO255.Gateway.csproj", "MS.AFORO255.Gateway/"]
RUN dotnet restore "MS.AFORO255.Gateway/MS.AFORO255.Gateway.csproj"
COPY . .
WORKDIR "/src/MS.AFORO255.Gateway"
RUN dotnet build "MS.AFORO255.Gateway.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MS.AFORO255.Gateway.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "/app/AFORO255.MS.TEST.Gateway.dll"]